# Generated by Django 5.0.2 on 2024-06-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('stripe_subscription_id', models.CharField(max_length=255)),
                ('plan', models.CharField(choices=[('monthly', 'Monthly'), ('sixmonth', 'Sixmonth'), ('yearly', 'Yearly')], max_length=120)),
                ('amount', models.IntegerField()),
                ('is_expired', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_period_end', models.DateTimeField()),
            ],
        ),
    ]
