version: "3.8"

services:

  rabbitmq:
    restart: always
    image: "rabbitmq:3-management"
    container_name: "rabbitmq_container"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    networks:
      - auth
      - common_network
      
  redis:
    image: redis:latest
    container_name: user-redis
    ports:
      - "6379:6379"
    networks:
      - auth

  auth_service:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend:auth_service
    container_name: auth-service
    command: sh -c "chmod +x ./migrate.sh && chmod +x ./entrypoint.sh && sh ./migrate.sh && ./entrypoint.sh"
    ports:
      - 8001:8000
    restart: always
    env_file:
      - .env
    volumes:
      - ./backend/auth_service:/app
    depends_on:
      - redis
      - rabbitmq
    networks:
      - auth
      - common_network

  user_celery_worker:
    restart: always
    build:
      context: .
    env_file:
      - .env
    container_name: user-celery-worker
    command: celery -A auth worker --loglevel=info
    volumes:
      - ./backend/auth_service:/code-auth-service
    depends_on:
      - redis
    networks:
      - auth
      - common_network

networks:
  auth:
    name: auth
  common_network:
    external: true
