# Generated by Django 5.0.2 on 2024-05-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_otp_verify',
            field=models.BooleanField(default=True),
        ),
    ]
